config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_scope :user do
    # This block of code is mandatory for devise to support logout in rails 7
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users

  # Defines the root path route ("/")
  resources 'general_shopping_list', only: %w[index] 
  resources 'public_recipes', only: %w[index] 
  resources 'recipes', only: %w[index show destroy new create] do
    resource 'recipe_foods', only: %w[create destroy]
  end
  resources 'foods', only: %w[index new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_food, dependent: :delete_all
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true, length: { maximum: 250 }
  validates :price, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_food, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 1 }
  validates :cooking_time, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 1 }
  validates :description, presence: true, allow_blank: true
  validates :public, inclusion: { in: [true, false] }

  def getfoods(id)
    food_list = []
    recipe_foods = RecipeFood.where(recipe_id: id)

    recipe_foods.each do |foods|
      Food.where(id: foods.food_id).each do |food|
        food_list.push(food)
      end
    end
    food_list
  end

  def total_price(food_list)
    total = 0
    food_list.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @sigle_food_price = food.price * recipe_food.quantity
      end
      total += @sigle_food_price
    end
    total
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :delete_all
  has_many :recipes, dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:first_name, :last_name,
                                             { address_attributes: %i[country state city area postal_code] }])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :render_food_not_found
  before_action :authenticate_user!

  # Get all foods for a logged in user
  def index
    @owned_food = current_user.foods.all
  end

  # Adding a new food form
  def new
    @food = Food.new
  end

  # Delete Food by ID
  def destroy
    @delete_food = current_user.foods.find(params['id'])
    if @delete_food.destroy
      redirect_to foods_path,
                  flash: { success: 'food has been deleted' }
    else
      redirect_to foods_path,
                  flash: { error: 'food not found' }
    end
  end

  # submit food form
  def create
    @new_food = current_user.foods.new(food_params)

    if @new_food.save
      redirect_to foods_path,
                  flash: { success: "#{@new_food.name} has been added ,
                   with a price of #{@new_food.price}$ per 1 #{@new_food.measurement_unit}" }
    else
      redirect_to new_foods, flash: { error: @new_food.errors.full_messages }
    end
  end

  # Error when deleting a not found food id
  def render_food_not_found
    redirect_to foods_path,
                flash: { error: 'food not found' }
  end

  # Sanitize food params before saving in tha database
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/general_shopping_list_controller.rb
class GeneralShoppingListController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(user_id: current_user.id)
    @items = RecipeFood.includes(:food).where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @items.map(&:food_id))
    @price = total_price(@items)
  end

  private

  def total_price(items)
    price = 0
    items.each do |recipe_food|
      price += Food.find(recipe_food.food_id).price * recipe_food.quantity
    end
    price
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recent_recipe = Recipe.where(public: true).order(created_at: :desc).limit(3)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @all_public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]),
                  flash: { success: "#{@recipe_food.food.name} has been attached successfully!" }
    else
      redirect_to recipe_path(params[:recipe_id]),
                  flash: { error: "Failed to attach #{@recipe_food.food.name}!" }
    end
  end

  def destroy
    @recipe_food = RecipeFood.find params[:id]
    @recipe_food.destroy!
    redirect_to recipe_path(params[:recipe_id]),
                flash: { success: "#{@recipe_food.food.name} has been detached successfully!" }
  end

  private

  def recipe_food_params
    params.permit(:food_id, :recipe_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all.where(user: current_user)
  end

  def show
    @recipe = Recipe.includes([:recipe_food]).find params[:id]
    @recipe_foods = @recipe.recipe_food
    @recipe_food = RecipeFood.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path,
                  flash: { success: "#{@recipe.name} has been successfully created!" }
    else
      redirect_to new_recipe_path, flash: { error: @recipe.errors.full_messages }
    end
  end

  def destroy
    @recipe = Recipe.find params[:id]
    @recipe.destroy!
    redirect_to recipes_path, flash: { success: "#{@recipe.name} has been deleted successfully!" }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<h1>Your Food List</h1>
<p>Hello <b> <%= current_user.name %> </b>, Here you can see all of the foods added by you</p>

<div class="new-container d-flex flex-row-reverse">
<%= link_to raw("<i class=\"fa-solid fa-plus\"></i> Add Food"), new_food_path ,:class => 'btn btn-md btn-success my-4', id: 'add-food' %>
</div><table class="table table-bordered table-light text-center">
  <thead>
    <tr>
      <th class="bg-dark text-light" scope="col">#ID</th>
      <th class="bg-dark text-light" scope="col">Name</th>
      <th class="bg-dark text-light" scope="col">Measurement unit</th>
      <th class="bg-dark text-light" scope="col">Price</th>
      <th class="bg-dark text-light" scope="col">Quantity</th>
      <th class="bg-dark text-light" scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
   <% if (@owned_food.length() < 1) %>
      <tr>
        <td colspan="6" class="text-center">You Don't Have Any Food Yet 😔</td>
     </tr>
   <% end %>
    
  <% @owned_food.each do |food| %>
    <tr>
      <th scope="row"><%= food.id %></th>
        <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
       <td><%= food.price %> $</td>
      <td><%= food.quantity %></td>
       <td><%= button_to raw('<i class=\"fa-solid fa-trash-can"\></i> Delete'),food_path(food.id), :method => :delete,:class => "btn btn-sm btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-solid-success alert-bold" role="alert">
    <p class=" mt-3 alert alert-danger"><%= flash[:error].each { |n| puts "#{n.to_s}" } %></p>
  </div>
<% end %>
<h1>Add New Food</h1>
<p>Add your personal food to create a recipe</p>

<div class="form-signin col-4  mt-5">
  <%= form_with model: @food do |form| %>
    <%= form.text_field :name, required: true, autofocus: true, class: ' mb-3 form-control', id: "name", autocomplete: "Food name", placeholder: "Food name" %>
    <%= form.text_field :measurement_unit, required: true, class: ' mb-3 form-control', id: "measurement", autocomplete: "Measurement unit", placeholder: "Measurement unit" %>
    <%= form.number_field :price, required: true, class: ' mb-3 form-control', id: "price", autocomplete: "Price", placeholder: "Price" %>
    <%= form.number_field :quantity, required: true, class: ' mb-3 form-control', id: "quantity", autocomplete: "Quantity", placeholder: "Quantity" %>
    <%= form.submit "Save", class: 'w-100 mb-3  btn btn-md btn-success', id: 'submit' %>
  <% end %>
</div>

app/views/general_shopping_list/index.html.erb
<h1>General Shopping List</h1>
<p>Here you can find all of the missing foods for your recipes</p>

<div class="d-flex text-center align-items-center gap-5 justify-content-center">
<h4 class="m-3">Amount of food items to buy : <b class='text-danger'> <%= @items.count %> </b></h4>
<h4 class="m-3">Total price of food needed : <b class='text-danger'> <%= @price %> $</b></h4>


</div> 
<div class="text-center d-flex align-items-center justify-content-center">
<table class="table table-bordered  table-light mt-5" style='width:500px'>
  <thead>
    <tr>

      <th class="bg-dark text-light" scope="col">Food</th>
      <th class="bg-dark text-light" scope="col">Quantity</th>
      <th class="bg-dark text-light" scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
    <tr>

      <td><%= item.food.name %></td>
      <td><%= item.quantity %> <%= item.food.measurement_unit %></td>
      <td><%= item.food.price * item.quantity%> $</td>
    </tr>
  <% end %>
  </tbody>
</table>
</div> 

app/views/home/index.html.erb
<div class="mt-4">
  <div class="p-4 p-md-5 mb-4 rounded text-white bg-dark">
    <div class="col-md-8 px-0">
      <h1 class="display-4 fst-italic">Welcome To the #1 Food Recipes website</h1>
      <p class="lead my-3">Discover created recipes … or start your own recipe creations , easily
        modifying ingredients and steps as you need! Save them all in one place
        and cook them with joy</p>
      <div class="lead mb-0"><a href="/public_recipes" class="btn btn-primary text-white fw-bold">Check Public Recipes</a></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">

    <div class="d-flex justify-content-center align-items-center flex-column mt-5">
      <h2>
        Recent Recipes</h2>
      <% @recent_recipe.each do |recipe| %>
        <%= render partial: "layouts/partials/recipe_card", locals: {
    recipe: recipe,
  } %>
      <% end %>
    </div></div>
  <div class="col-md-6 d-flex align-items-center">
    <div
      class="
        d-flex
        justify-content-center
        align-self-center
        text-center
        flex-column
        mt-5
      "
    >
      <h2>
        Why Us ?</h2>
      <p>Everyone is welcome at the Recipe App table: people of all races,
        religions, genders, sexual orientations, ages, backgrounds, and
        abilities. We strive to be a resource for every home cook, and we
        consciously work to make this inclusion felt in every part of the site,
        from the individuals we hire to the recipes we share. We’re not
        perfect, but we hope to get more right than we get wrong</p>
      <h2>
        Our History</h2>
      <p>Recipe App was founded in 2022 by <a href="https://github.com/ichala" target="_blank">Ali Jendoubi</a> and <a href="https://github.com/aimalamiri" target="_blank">Aimal Amiri
</a> as a home cooking
        blog . Today, Recipe App has
        grown into a trusted resource for home cooks with more than 3,000
        tested recipes, guides, and meal plans, drawing over 15 million readers
        each month from around the world. We’re supported by a diverse group of
        recipe developers, food writers, recipe and product testers,
        photographers, and other creative professionals.</p>
        <h2>
        Recipe Development</h2>
        <p>Our recipes primarily use fresh, unprocessed ingredients but we also believe there is a time and a place for canned, frozen, and other prepared ingredients. We believe in a diet that includes a wide variety of foods: real butter and cream, extra virgin olive oil, eggs, lots of fruits and vegetables, and protein from meat, fish, beans, and cheese. Plus cake for dessert.</p>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"/>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <title>Recipe App</title>
</head>

<body style='background:#F8F8F8;'>
<%= render 'layouts/layout/header' %>
<main  class='container content'>
  <% if notice %>
    <p class=" mt-3 alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="mt-3 alert alert-danger"><%= alert %></p>
  <% end %>
  <% if flash[:success] %>
    <div class="alert alert-solid-success alert-bold" role="alert">
      <p class=" mt-3 alert alert-success"><%= sanitize(flash[:success]) %></p>
    </div>
  <% end %>
  <% if flash[:error] %>
    <div class="alert alert-solid-success alert-bold" role="alert">
      <p class=" mt-3 alert alert-danger"><%= flash[:error].each{ |n| puts "#{n.to_s}" } %></p>
    </div>
  <% end %>

  <%= yield %>
</main >
<%= render 'layouts/layout/footer' %>
<script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
</script>

</body>
</html>

app/views/layouts/layout/_footer.html.erb
<footer class="footer py-3 bg-dark">
  <div class="container">
    <span class="text-muted">Created By <a href="https://github.com/ichala" target="_blank">@Ali Jendoubi</a> and <a href="https://github.com/aimalamiri" target="_blank">@Aimal Amiri
</a></span>
  </div>
</footer>

app/views/layouts/layout/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Recipe App</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav  me-auto  mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, :class => (controller.controller_name == 'home' ? 'nav-link active' : 'nav-link') %>
        </li>
         <li class="nav-item">
          <%= link_to "Public Recipes", public_recipes_path, :class => (controller.controller_name == 'public_recipes' ? 'nav-link active' : 'nav-link') %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Foods", foods_path, :class => (controller.controller_name == 'foods' ? 'nav-link active' : 'nav-link') %>
        </li>
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, :class => (controller.controller_name == 'recipes' ? 'nav-link active' : 'nav-link') %>
        </li>
       
        <li class="nav-item">
          <%= link_to "General Shopping List", general_shopping_list_index_path ,:class => (controller.controller_name == 'general_shopping_list' ? 'nav-link active' : 'nav-link') %>
        </li>
        <% end %>
        
      </ul>

      <% if user_signed_in? %>
        <%= button_to "logout", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger my-2 my-sm-0' %>
      <% else %>
        <%= link_to "Login", new_user_session_path, method: :get, :class => 'btn btn-primary my-2 my-sm-0' %>
         <%= link_to "Signup", new_user_registration_path , method: :get, :class => 'btn btn-primary my-2 my-sm-0 mx-2' %>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/partials/_recipe_card.html.erb
<div class="card border-secondary mb-3 w-100" >
  <div class="card-header  d-flex justify-content-between">
  <div>
  Recipe#<b><%= recipe.id %></b> by <b><%= recipe.user.name %></b></div>
  <p><%= distance_of_time_in_words(recipe.created_at, DateTime.now) %></p></div> 
  <div class="card-body text-secondary">
    <h5 class="card-title"><%= recipe.name %></h5>
    <p class="card-text"><%=h truncate(recipe.description, :length => 160) %></p>
  </div>
    <div class="card-footer d-flex  align-items-center justify-content-between">
    <div class=" d-flex align-items-center justify-content-center px-4 ">
      <span class="badge badge-dark bg-dark m-1">Total food items: <%= recipe.getfoods(recipe.id).count %></span>
       <span class="badge badge-success bg-success m-1">Total price: 
        <%=  recipe.total_price(recipe.getfoods(recipe.id)) %>$
      </span>
      </div>
      
      <%= link_to raw('<i class=\"fa-solid fa-trash-can"\></i> More Details'),recipe_path(recipe.id),:class => "btn btn-sm btn-primary" %>
    </div>  
    </div> 

app/views/public_recipes/index.html.erb
<h1>Public Recipes</h1>
<p>Here you can find all of the public recipes</p>

<div class="d-flex justify-content-center flex-column mt-5">
<% @all_public_recipes.each do |recipe|%>
<%= render partial: "layouts/partials/recipe_card", locals: {
    recipe: recipe,
  }%>
    <% end %>
    
</div>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<p>List of your recipes</p>

<div class="text-end">
  <%= link_to raw("<i class=\"fa-solid fa-plus\"></i> Add Recipe"), new_recipe_path ,:class => 'btn btn-md btn-success my-4', id: 'add-recipe' %>
</div>
<table class="table table-bordered table-light">
  <thead>
  <tr >
    <th class="bg-dark text-light" scope="col">#</th>
    <th class="bg-dark text-light" scope="col">Name</th>
    <th class="bg-dark text-light" scope="col">Preparation Time</th>
    <th class="bg-dark text-light" scope="col">Cooking Time</th>
    <th class="bg-dark text-light" scope="col">Is Public</th>
    <th class="bg-dark text-light" scope="col">Owner</th>
    <th class="bg-dark text-light" scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @recipes.each do |recipe| %>
    <tr>
      <th scope="row"><%= recipe.id %></th>
      <td><%= recipe.name %></td>
      <td><%= recipe.preparation_time %> Minutes</td>
      <td><%= recipe.cooking_time %> Minutes</td>
      <td><%= recipe.public %></td>
      <td><%= recipe.user.name %></td>
      <td class="d-flex">
        <a href="<%= recipe_path(recipe.id) %>" class="btn btn-sm btn-primary show"><i class="fa-solid fa-eye"></i> Show</a>
        <%= button_to recipe_path(recipe.id), :method => :delete, :class => "btn btn-sm btn-danger mx-1 delete" do %>
          <i class="fa-solid fa-trash"></i> Delete
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/recipes/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-solid-success alert-bold" role="alert">
    <p class=" mt-3 alert alert-danger"><%= flash[:error].each { |n| puts "#{n.to_s}" } %></p>
  </div>
<% end %>
<h1>Add new recipe</h1>
<p>Add a recipe by filling the form bellow</p>

<div class="form-signin col-4  mt-5">
  <%= form_with model: @recipe do |form| %>
    <%= form.text_field :name, required: true, autofocus: true, class: ' mb-3 form-control', id: "name", autocomplete: "recipe_name", placeholder: "Recipe name" %>
    <%= form.number_field :preparation_time, required: true, class: 'mb-3 form-control', id: "preparation_time", autocomplete: "preparation_tim", placeholder: "Preparation time in minutes" %>
    <%= form.number_field :cooking_time, required: true, class: ' mb-3 form-control', id: "cooking_time", autocomplete: "cooking_tim", placeholder: "Cooking time in minutes" %>
    <%= form.text_area :description, class: ' mb-3 form-control', id: "description", placeholder: "Description" %>
    <div class="form-check form-switch form-check-reverse mb-3 ">
      <label class="form-check-label" for="public">Public</label>
      <%= form.check_box :public, class: 'form-check-input', id: "public", checked: true %>
    </div>
    <%= form.submit "Save", class: 'w-100 mb-3  btn btn-md btn-success', id: 'submit' %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h1>Recipes</h1>
<p>List of your recipes</p>

<h2 class="text-center"><%= @recipe.name %></h2>
<div class="row">
  <div class="col-6">
    It takes <span class="fw-bold"><%= @recipe.preparation_time %> minutes</span> to prepare, and
    <span class="fw-bold"><%= @recipe.cooking_time %> minute</span> more time to cook.
    <div class="my-3">
      Created by <span class="fw-bold"><%= @recipe.user.name %></span>
    </div>
    <div class="my-3">
      Created  <span class="fw-bold"><%= distance_of_time_in_words(@recipe.created_at, DateTime.now) %></span> ago
    </div>
    <div class="my-3">
      Updated  <span class="fw-bold"><%= distance_of_time_in_words(@recipe.updated_at, DateTime.now) %></span> ago
    </div>
  </div>
  <div class="col-6 d-flex justify-content-end">
    <div class="form-check form-switch form-check-reverse">
      <label class="form-check-label" for="public">Public</label>
      <input class="form-check-input" type="checkbox" id="public" <%= 'checked' if @recipe.public %> disabled>
    </div>
  </div>

  <div class="col-12 py-5">
    <h5>Step to go</h5>
    <p><%= @recipe.description %></p>
  </div>

  <div class="text-end px-0">
    <% if @recipe.user == current_user %>
      <button type="button" class="btn btn-primary mb-3 mr-n1" data-bs-toggle="modal" data-bs-target="#ingredient">
        Add ingredient
      </button>
    <% end %>

    <div class="modal fade" id="ingredient" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <%= form_with url: recipe_recipe_foods_path(@recipe.id), method: :post do |form| %>
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Attach ingredients</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= form.select :food_id, Food.order(:name).pluck(:name, :id), {}, class: ' mb-3 form-select', placeholder: "Select a food item" %>
              <%= form.number_field :quantity, required: true, class: ' mb-3 form-control', id: "quantity", autocomplete: "Quantity", placeholder: "Quantity" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= form.submit "Save", class: 'btn btn-md btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <table class="table table-bordered table-light text-center">
    <thead>
    <tr>
      <th class="bg-dark text-light" scope="col">Food</th>
      <th class="bg-dark text-light" scope="col">Quantity</th>
      <th class="bg-dark text-light" scope="col">Value</th>
            <% if @recipe.user == current_user %>
       
  
      <th class="bg-dark text-light" scope="col">Action</th>     <% end %>
    </tr>
    </thead>
    <tbody>
    <% if (@recipe.recipe_food.length() < 1) %>
      <tr>
        <td colspan="6" class="text-center">No food is attached 😔</td>
      </tr>
    <% end %>

    <% @recipe.recipe_food.each do |item| %>
      <tr>
        <th scope="row"><%= item.food.name %></th>
        <td><%= item.quantity %></td>
        <td>$<%= item.quantity * item.food.price %></td>
         <% if @recipe.user == current_user %>
        <td><%= button_to raw('<i class=\"fa-solid fa-trash-can"\></i> Delete'), recipe_recipe_foods_path(@recipe.id, id: item.id), :method => :delete, :class => "btn btn-sm btn-danger" %></td>
       <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>